# Generated by Django 4.2.1 on 2023-07-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Название темы')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания темы')),
            ],
        ),
    ]
