# Generated by Django 4.2.1 on 2023-07-01 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tema',
            options={'verbose_name': ['Темы'], 'verbose_name_plural': ['Темы']},
        ),
    ]
