# Generated by Django 4.2.1 on 2023-07-01 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0002_alter_tema_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tema',
            options={'ordering': ['-id'], 'verbose_name': ['Темы'], 'verbose_name_plural': ['Темы']},
        ),
        migrations.CreateModel(
            name='Otvet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Автор')),
                ('text', models.CharField(max_length=2000, verbose_name='Текст ответа')),
                ('image', models.ImageField(blank=True, null=True, upload_to='%y%m%d', verbose_name='Картинка')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_app.tema')),
            ],
            options={
                'verbose_name': ['Ответ'],
                'verbose_name_plural': ['Ответы'],
                'ordering': ['-created_date'],
            },
        ),
    ]
