# Generated by Django 4.2.1 on 2023-07-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0003_alter_tema_options_otvet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otvet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='%y/%m/%d/', verbose_name='Картинка'),
        ),
    ]
